### PR TITLE
Respect jsx setting in tsconfig

### LINKED ISSUE #117: Does "react-jsx" work?
This is a very cool tool, thanks for creating it! I was wondering about compiling React, is setting `"jsx": "react-jsx"` in `tsconfig.json` supposed to work? I'm getting the following error message when I try to compile a `.tsx` file:

```
Error: @rollup/plugin-typescript TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

Let me know if you need a repro.

### PR DESCRIPTION
**Pull request by huozhi**
Resolves #117 

Reading tsconfig if there's one from the working directory, and passdown the `compilerOptions.jsx` option value to typescript plugin to align the compilation result with what tsconfig specified.

Notice that we're using swc to compile the typescript now, so `"jsx": "preserve"` won't preserve the original jsx syntax but will still compile to js code. Here's the [thread about that feature on swc side](https://github.com/swc-project/swc/pull/5661).

### CODE REVIEW

File: src/rollup-config.ts [hunk 1]
```diff
@@ -130,6 +135,13 @@ function createInputConfig(
           classPrivateProperty: true,
           exportDefaultFrom: true,
         },
+        transform: {
+          react: {
+            runtime: ['react-jsx', 'react-jsx-dev'].includes(tsCompilerOptions?.jsx)
+              ? 'automatic'
+              : 'classic'
+          }
+        },
```
Comment (SukkaW) [inline src/rollup-config.ts:144]: https://github.com/SukkaW/rollup-plugin-swc/blob/eb4c8ae97d649b6f8e932824528bef9b53b018ba/src/index.ts#L101-L107

I am wondering if maybe I should include this in `rollup-plugin-swc3`. Any thoughts?

Comment (SukkaW) [reply src/rollup-config.ts:144]: I am going to let `rollup-plugin-swc3` respects `tsconfig` as well.

It is recommended to use `tsconfig: false` if the `bunchee` will supplies all the configuration and wants `swc3` to be headless.

Comment (huozhi) [reply src/rollup-config.ts:144]: Got it! thanks!
