### PR TITLE
fix: ignore test file in prepare

### LINKED ISSUE #398: Should `bunchee --prepare` ignore test file?
Like `index.test.ts`

### PR DESCRIPTION
**Pull request by hyoban**
Fixes #398

### CODE REVIEW

File: test/integration/prepare-ts-with-test-file/src/foo.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+export const foo = 'foo'
```
Comment (huozhi) [inline test/integration/prepare-ts-with-test-file/src/foo.ts:1]: We can delete foo.ts and bin/ as they're not relative for the tests

File: test/integration/prepare-ts-with-test-file/src/bar.test.ts [hunk 2]
```diff
@@ -0,0 +1,5 @@
+describe("foo", () => {
+  it("bar", () => {
+    expect(true).toBe(true);
+  });
+});
```
Comment (huozhi) [inline test/integration/prepare-ts-with-test-file/src/bar.test.ts:5]: can you also run prettier format? I think the column can be erased, also will this file run in tests suite?

File: test/integration/prepare-ts-with-test-file/src/index.test.ts [hunk 3]
```diff
@@ -0,0 +1,5 @@
+describe("foo", () => {
```
Comment (huozhi) [inline test/integration/prepare-ts-with-test-file/src/index.test.ts:1]: same, will this run? maybe change this to a spec file to cover `.spec.` case

File: src/utils.ts [hunk 4]
```diff
@@ -157,3 +157,7 @@ export const hasCjsExtension = (filename: string): boolean =>
 // TODO: add unit test
 export const baseNameWithoutExtension = (filename: string): string =>
   path.basename(filename, path.extname(filename))
+
+export const isTestFile = (filename: string): boolean =>
+  // include .test. or .spec. in filename
+  /\.(test|spec)\./.test(filename)
```
Comment (huozhi) [inline src/utils.ts:163]: need to test `baseNameWithoutExtension`, cause it can be `a.f.foo.spec.some.js` which looks like a random valid case.

```js
/\.(test|spec)$/.test(baseNameWithoutExtension(filename))
```

**Comment by hyoban** [comment]
All updated. Thanks for your review.

File: package.json [hunk 5]
```diff
@@ -106,7 +106,11 @@
       "^.+\\.(t|j)sx?$": [
         "@swc/jest"
       ]
-    }
+    },
+    "testPathIgnorePatterns": [
+      "/node_modules/",
+      "<rootDir>/test/integration/prepare-ts-with-test-file/"
```
Comment (huozhi) [inline package.json:112]: let’s ignore the tests from src/ folders under test/integration

File: test/integration/prepare-ts-with-test-file/src/index.react-server.ts [hunk 6]
```diff
@@ -0,0 +1 @@
+export const index = 'index.react-server'
```
Comment (huozhi) [inline test/integration/prepare-ts-with-test-file/src/index.react-server.ts:1]: Is this file used?

Comment (hyoban) [reply test/integration/prepare-ts-with-test-file/src/index.react-server.ts]: No, removed

File: package.json [hunk 7]
```diff
@@ -106,7 +106,11 @@
       "^.+\\.(t|j)sx?$": [
         "@swc/jest"
       ]
-    }
+    },
+    "testPathIgnorePatterns": [
+      "/node_modules/",
+      "<rootDir>/test/integration/"
```
Comment (huozhi) [inline package.json:112]: Only skip source folder
```suggestion
      "<rootDir>/test/integration/.*/*src"
```

**Review by huozhi — APPROVED** [review]
Thanks!
